#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from skill_arbiter.inventory import build_inventory_snapshot
from skill_arbiter.paths import REPO_ROOT


def _sync_state(row: dict[str, object]) -> str:
    legitimacy = str(row.get("legitimacy_status") or "").lower()
    ownership = str(row.get("ownership") or "").lower()
    action = str(row.get("recommended_action") or "").lower()
    if legitimacy == "official_trusted":
        return "aligned_official"
    if legitimacy == "owned_trusted":
        return "aligned_owned"
    if legitimacy == "third_party_trusted":
        return "cataloged_keep"
    if legitimacy == "third_party_watch" and action == "keep":
        return "watchlisted_keep"
    if legitimacy == "third_party_watch":
        return "pending_candidate"
    if ownership.startswith("official") or ownership.startswith("repo_owned"):
        return "needs_policy_review"
    return "manual_attention"


def render_matrix(payload: dict[str, object]) -> str:
    skills = [row for row in payload.get("skills", []) if str(row.get("local_presence") or "") == "installed"]
    skills.sort(key=lambda row: str(row.get("name") or "").lower())
    summary = {
        "official_trusted": 0,
        "owned_trusted": 0,
        "third_party_trusted": 0,
        "third_party_watch": 0,
    }
    for row in skills:
        legitimacy = str(row.get("legitimacy_status") or "").lower()
        if legitimacy in summary:
            summary[legitimacy] += 1
    lines = [
        "# VS Code Codex Skill Update Matrix",
        "",
        "This document is machine-generated by `scripts/generate_vscode_codex_skill_matrix.py`.",
        "It aligns the live installed Codex skills directory with the Skill Arbiter inventory model so both systems use the same catalog language.",
        "",
        "## Summary",
        "",
        f"- Generated: `{payload.get('generated_at', '')}`",
        "- Host ID: `<LOCAL_HOST_ID>`",
        f"- Installed skills tracked: `{len(skills)}`",
        f"- Official trusted: `{summary.get('official_trusted', 0)}`",
        f"- Owned trusted: `{summary.get('owned_trusted', 0)}`",
        f"- Third-party trusted: `{summary.get('third_party_trusted', 0)}`",
        f"- Third-party watch: `{summary.get('third_party_watch', 0)}`",
        f"- Active incidents: `{payload.get('incident_count', 0)}`",
        "",
        "## Installed Skill Matrix",
        "",
        "| Skill | Origin | Ownership | Legitimacy | Risk | Action | Sync State |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in skills:
        lines.append(
            "| `{name}` | `{origin}` | `{ownership}` | `{legitimacy_status}` | `{risk_class}` | `{recommended_action}` | `{sync_state}` |".format(
                name=row.get("name", ""),
                origin=row.get("origin", ""),
                ownership=row.get("ownership", ""),
                legitimacy_status=row.get("legitimacy_status", ""),
                risk_class=row.get("risk_class", ""),
                recommended_action=row.get("recommended_action", ""),
                sync_state=_sync_state(row),
            )
        )
    watch_rows = [row for row in skills if str(row.get("legitimacy_status") or "").lower() == "third_party_watch"]
    lines.extend(
        [
            "",
            "## Watchlisted Keep Rows",
            "",
        ]
    )
    if not watch_rows:
        lines.append("_None._")
    else:
        lines.extend(
            [
                "| Skill | Origin | Action | Reason |",
                "| --- | --- | --- | --- |",
            ]
        )
        for row in watch_rows:
            lines.append(
                "| `{name}` | `{origin}` | `{recommended_action}` | {reason} |".format(
                    name=row.get("name", ""),
                    origin=row.get("origin", ""),
                    recommended_action=row.get("recommended_action", ""),
                    reason=str(row.get("legitimacy_reason") or "").replace("\n", " "),
                )
            )
    return "\n".join(lines) + "\n"


def main() -> int:
    payload = build_inventory_snapshot()
    target = REPO_ROOT / "references" / "vscode-codex-skill-update-matrix.md"
    target.write_text(render_matrix(payload), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
