#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from skill_arbiter.inventory import build_inventory_snapshot
from skill_arbiter.paths import REPO_ROOT

PUBLIC_CATALOG_ADVISOR_NOTE = "_Live local advisor note omitted from public-shape catalog._"


def render_catalog(payload: dict[str, object]) -> str:
    skills = payload.get("skills", [])
    sources = payload.get("sources", [])
    incidents = payload.get("incidents", [])
    recent_work = payload.get("recent_work_skills", [])
    legitimacy = payload.get("legitimacy_summary", {})
    interop_sources = payload.get("interop_sources", [])
    lines = [
        "# NullClaw Skill Catalog",
        "",
        "This document is machine-generated by `scripts/generate_skill_catalog.py` from the live NullClaw inventory model.",
        "",
        "## Inventory Summary",
        "",
        f"- Generated: `{payload.get('generated_at', '')}`",
        "- Host ID: `<LOCAL_HOST_ID>`",
        f"- Skill records: `{len(skills)}`",
        f"- Source records: `{len(sources)}`",
        f"- Incident records: `{len(incidents)}`",
        f"- Recent-work-relevant skills: `{len(recent_work)}`",
        "",
        "## Legitimacy Summary",
        "",
        f"- Official trusted: `{legitimacy.get('official_trusted', 0)}`",
        f"- Owned trusted: `{legitimacy.get('owned_trusted', 0)}`",
        f"- Needs review: `{legitimacy.get('needs_review', 0)}`",
        f"- Blocked hostile: `{legitimacy.get('blocked_hostile', 0)}`",
        "",
        "## Advisor Note",
        "",
        PUBLIC_CATALOG_ADVISOR_NOTE,
        "",
        "## Interop Surfaces",
        "",
        "| Surface | Scope | Presence | Notes |",
        "| --- | --- | --- | --- |",
    ]
    for row in interop_sources:
        lines.append(
            "| `{source_id}` | `{compatibility_surface}` | `{local_presence}` | {notes} |".format(
                source_id=row.get("source_id", ""),
                compatibility_surface=row.get("compatibility_surface", ""),
                local_presence=row.get("local_presence", ""),
                notes=", ".join(str(item) for item in row.get("notes", [])),
            )
        )
    lines.extend(
        [
            "",
        "## Current Sources",
        "",
        "| Source | Type | Origin | Version | Presence | Risk | Action |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in sources:
        lines.append(
            "| `{source_id}` | `{source_type}` | `{origin}` | `{version_or_commit}` | `{local_presence}` | `{risk_class}` | `{recommended_action}` |".format(
                **row
            )
        )
    if recent_work:
        lines.extend(
            [
                "",
                "## Recent-Work Skills",
                "",
                ", ".join(f"`{name}`" for name in recent_work),
            ]
        )
    lines.extend(
        [
            "",
            "## Current Skill Matrix",
            "",
            "| Skill | Source Type | Ownership | Legitimacy | Presence | Drift | Risk | Action |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in skills:
        lines.append(
            "| `{name}` | `{source_type}` | `{ownership}` | `{legitimacy_status}` | `{local_presence}` | `{drift_state}` | `{risk_class}` | `{recommended_action}` |".format(
                **row
            )
        )
    if incidents:
        lines.extend(
            [
                "",
                "## Active Incidents",
                "",
                "| Severity | Subject | Ownership | Legitimacy | Summary |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for row in incidents:
            lines.append("| `{severity}` | `{subject}` | `{ownership}` | `{legitimacy_status}` | {summary} |".format(**row))
    return "\n".join(lines) + "\n"


def main() -> int:
    payload = build_inventory_snapshot()
    output = render_catalog(payload)
    target = REPO_ROOT / "references" / "skill-catalog.md"
    target.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
